### ISSUE TITLE
Ents have trouble hitting dragons

### ISSUE THREAD

**Issue by AgonyAunt** [AgonyAunt/Sigil-City-of-Doors-PW#24]
Presume also applies to any race with a larger hitbox. Large vs large could be a problem here as their hit range might not be enough.

Consider tweaking the hit range of ents, but not too much, otherwise smaller races could be getting hit running away when they should be technically out of range.

Test properly before release on this one.

**Comment by ghost** [comment]
I could have a look at this, checking the wiki entry on appearance.2da there are some interesting entries:

PERSPACE -  How much space they give something else, in meters, diameter from model base 
CREPERSPACE - How much other things give it, in meters, diameter from model base
HITDIST -   Preferred distance for attackers to hit the creature, in meters from model base
PREFATCKDIST - Preferred attack distance, in meters

I'll have a play around with the values and see if I can get rid of the issue and remove the need for closeness too

**Comment by AgonyAunt** [comment]
Assigned to you then, got for it ;)

I already tweaked one of these settings and had no further reports of problems.  But feel free to test it with current settings and see if it works better if you change things further.

**Comment by AgonyAunt** [comment]
Also if tweaking the Ents to compare with Dragons, remember to also then see how this affects regular sized races like humans.  Do some running away from the ents, see what range they can hit you from for example.

**Comment by ghost** [comment]
This was caused by the dragon's PERSPACE value being set too high, reducing it to 0.4 fixes the issue. I have made that change and a couple of others in appearance.2da that I think would be worth considering.

In adition to this I would recommend setting the  CREPSPACE to either 1 (down from 1.5) or more preferably 0.8. This determines how close the model is allowed to get to another without closeness turned on. This will allow bronze dragons to get slightly closer than optimal from the front (head slightly inside a human's) but allows others to get fairly close to the side of it (flanking should be improved). 

The small demilich (Mimir) seem to have their CREPSPACE set very high as well a value of 0.6 will allow for normal humanoids to approach to about the same distance as another humanoid. This has no effect of the talk distance, it simply improves path-finding.

young bronze CREPSPACE set to 0.8
https://dl.dropboxusercontent.com/u/50926122/dragon0.8.jpg

young bronze CREPSPACE set to 1.0
https://dl.dropboxusercontent.com/u/50926122/dragon%201.0.jpg

**Comment by ghost** [comment]
Apparently this was also a problem for Blue dragons. should I post a thread on the forums to see if any of the others have such issues, or does that reveal a possible exploit?

**Comment by AgonyAunt** [comment]
No worries about exploit, its not a major issue.  Feel free to ask players though if they have noticed any similar problems with other races.

**Comment by AgonyAunt** [comment]
@lukehall - any further update on this?

**Comment by ghost** [comment]
No one else has replied to the thread as far as I'm aware. PERSPACE 0.4 will fix this for both dragons if I remember correctly (at work so can't check now and will not be back until very late tonight), otherwise all is as per my previous comment on the 17th.

**Comment by AgonyAunt** [comment]
Cool. Ok, i can make this change by myself then, no need to submit any files. Ill assign the issue to myself.

Thanks for your work on this.
