### ISSUE TITLE
Death on rest.... can we check for it and apply rez?

### ISSUE THREAD

**Issue by AgonyAunt** [AgonyAunt/Sigil-City-of-Doors-PW#245]

**Comment by Electrohydra** [comment]
Adding this to the OnPlayerRest script should fix it. I ran tests and it seems to work (at least in my minimalist module, not sure how it will interact with Sigil's stuff. Particularly the closing the death screen takes into account vanilla NWN2 death system, might need a tweek.

// Returns the player character to life if the rest killed him (Because of lost CON)
void ResurectIfDead(object oPC)
{
    if (GetIsDead(oPC))
    {
        ApplyEffectToObject(DURATION_TYPE_INSTANT, EffectResurrection(), oPC);
        AssignCommand(oPC, ActionRest());  // Restarts the rest
        DelayCommand(2.501f, CloseGUIScreen(oPC, "SCREEN_DEATH_DEFAULT")); // Closes   //the death GUI just after it pops up
    }
}

void main()
{
    object oPC = GetLastPCRested();
    if (GetLastRestEventType() == REST_EVENTTYPE_REST_STARTED)
    {
        DelayCommand(0.1f, ResurectIfDead(oPC));
    }
}

**Comment by AgonyAunt** [comment]
Interesting. Thanks.

**Comment by AgonyAunt** [comment]
Hmm.. why bother with the GetLastRestEventType() call? Why not just check for GetIsDead?

**Comment by AgonyAunt** [comment]
I've just gone with this

```
if (GetIsDead(oPC)) 
{
    ApplyEffectToObject(DURATION_TYPE_INSTANT, EffectResurrection(), oPC);
}
```

Should do the same shouldn't it?

If you get ressed the gui should close anyway, and no need to restart resting.... i think.

**Comment by Electrohydra** [comment]
The GUI doesn't close on it's own (at least, in a simple module), which is why I had to make a call to close it (otherwise the player would need to either pick the Respawn or Exit Game options to close the GUI).

The GetLastRestEventType() is to be more efficient. OnPlayerRest is called at both the start of the rest and the end of the rest, so using GetLastRestEventType() makes sure the rest of the code only fires when the player starts his rest (which is when he could potentially die). No need to run the delayed command if you don't need to.

**Comment by Electrohydra** [comment]
Actually I believe the issue with the GUI is that it probably does close on resurrection (I assume the resurrection code closes it), but at least with the code I was using you are resurrected only 0.1 seconds after you die (to make it as seamless as possible), but the vanilla OnDeath code uses DelayCommand 2.5f to bring up the death GUI. So you would need either to close the GUI explicitly as I did, change the DelayCommand to resurect to 2.6f, or change the OnDeath code to bring up the death GUI instantly instead of after 2.5 seconds (if that's not already done on Sigil).

**Comment by Electrohydra** [comment]
Sorry for the triple post, I think I found a better solution to make it a lot nicer, and never open the death GUI in the first place. Just throw a check in the onDeath code that pops up the GUI to not pop it up if the PC is alive.
