### ISSUE TITLE
Ancestral Weapon (barb power) causes removal of other axes

### ISSUE THREAD

**Issue by Ceremorph** [AgonyAunt/Sigil-City-of-Doors-PW#321]
(Posted by alkalin)

**Comment by AgonyAunt** [comment]
Just caught this one while looking at my mail.

Working as intended, it removes your weapon before bringing in the new one.

I thought i had added code so that when it dissapeared it restored the old one... if i did though, it does it by grabbing the object id. It would then do an equip on the original weapon using its object id. However, if you are doing any other action at the same time, i suppose it could fail.

To be honest though, was so long ago, can't remember. However, i do remember playing a barb with this power and not having any issue. Either i had my regular weapon hotkeyed, or it was working fine.

**Comment by Ceremorph** [comment]
Agony, that's not what the comment was, sorry. When rage ends, the item in the off hand is unequipped (only viable to monkey grip users). The script is a little odd, defining oWeapon over and over... if you manage to look at it with this in mind, that would be cool.

**Comment by AgonyAunt** [comment]
Sorry, didn't notice the assignment. But i don't even have NWN2 installed anymore. Not sure why i was defining oWeapon over and over, but i probably had reasons, unless someone has been playing with my script.
