### ISSUE TITLE
Stalwart Defender New Powers Bug

### ISSUE THREAD

**Issue by Ceremorph** [AgonyAunt/Sigil-City-of-Doors-PW#331]
From Otyugh:
When you are using whirlwind with stalwart defender, you can click invigorating challenge or defensive stance to trigger another whirlwind immediatelly. First click on either doesn't expend the use of defensive stance nor invigorating challenge, just triggers another whirlwind. Second click expends either one and triggers a third whirlwind in rapid succession. But in doing so, you won't actually use invigorating challenge nor defensive stance, it just repeats whirlwinds.

I'm not one to complain about having 3 whirlwinds a round, but that's definitely a bug. tongue.gif

I'd test with other feats too, if I had those to test with. But if I had to make a guess: it's probably something about queueing, since neither of those feats try to queue, while still having an animation, rather they try to trigger at the instant you use them, even if you're unable to, so it probably confuses the game to restart last ability that was "attempted to be interrupted".

**Comment by Clangeddin** [comment]
This was fixed a while ago, I think. Defensive Stance and Vigorous Challenge now clear all the caster's actions when used.

EDIT: Actually, nevermind that, the bug is still there, geez... now how to figure out how to fix this...
EDIT 2: I think I managed to fix it. I just set whirlwind to a 6 seconds cooldown and set uses per day to -1
