### ISSUE TITLE
Pack Leader Bonus Feats

### ISSUE THREAD

**Issue by Ceremorph** [AgonyAunt/Sigil-City-of-Doors-PW#340]
Need to add epithet feats to races that qualify for this, and add feat prereq column to cls_feat 2da, as well as change type to 3 for the three bonus feats to ensure they're granted.

**Comment by Ceremorph** [comment]
Also:
Battle Howl now correctly offers a +3 bonus however, the DC is still set at 20.
Hunting Lope still does not reactivate after other movement speed modifies are applies. This means that after a slow effect or haste effect wears off the character loses his 40% movement speed boost. This also happens after you have been encumbered.
Winter Wolf Breath DC is still not calculated correctly, (it says its 10 on my lvl 30 winter wolf). The description also says that the DC is based on charisma where it should be based on constitution (All breath weapons in DnD are con based with a handful of exceptions -_0)

**Comment by Clangeddin** [comment]
Ok, took care of almost everything except Hunting Lope.
Winter Wolf Breath also had the spell resistance check still there (even though it shouldn't have).
Battle Howl was set to a fixed 4 rounds duration and 20 DC, rather than being based on Charisma.
As for the special bonus feat, I made a new epiteth feat that will be automatically assigned to pack leader at level 3. This feat will check the subrace and give the proper bonus feat regardless of requirements (mobility for blink dog, improved knockdown for worg and cold immunity for winter wolf).
Upload coming soon.
