### ISSUE TITLE
Gatecrasher Planar Survival

### ISSUE THREAD

**Issue by Ceremorph** [AgonyAunt/Sigil-City-of-Doors-PW#353]
Check resistances are set to apply properly.

**Comment by Clangeddin** [comment]
The effect was set to supernatural rather than extraordinary. This may have lead to issues where you could keep the effect of the feat even after you rebuilded the character .

Also, since the feat is meant to be self-only, I changed the recipient of the effect to OBJECT_SELF rather than spell target.
