### ISSUE TITLE
New Warlock Invocations - possible issues

### ISSUE THREAD

**Issue by AgonyAunt** [AgonyAunt/Sigil-City-of-Doors-PW#38]
From forum post: http://z13.invisionfree.com/nwn2planescape/index.php?showtopic=9223

By Taurus Daggerknight:

My apologies if this is in the wrong section or if this has been brought up before (Didn't see a thread on it, and most of the people I've spoken to seem to know little about the new ones).

First off; the concepts behind the new invocations are sweet. Baelful Gaes and Dark Discorp-whatever-its called sound great.....on paper. In practice:

1) Baeful Gaes needs to be explained more on its selection page, as it doesn't say what the DC is (unless I missed something). Furthermore, is the STR damage actually permanent as in, irreversible ever, or just an energy drain type effect? It would also be nice if we could get some RP guidelines in its description regarding what sort of things the warlock can or can't order the new thrall into doing, or if the victim remembers anything once they are free. 

2) Dark Discorp is just never going to be a viable option, because of how far it reduces your str. I get that this was done to relfect pnp, or that its done to prevent people from turning into invincible clouds of death, but in practice, it means that no person high enough in level to take it will ever be able to move. Anyone up that high has accumulated a fair amount of gear. It doesn't matter how good you are at not being a pack rat; just the stuff you're wearing has weight. An STR of 5 means you are encumbered the second you shift, and considering enemies at that level deal energy damage and stuff anyway, I'm not sure that's a particularly good trade. 

Is there any chance that this will be under review/ changed in the near future? 

Also, are all planned spells/ invocations sticking exclusively to the rulebooks, or are there going to be any in-house created ones?

**Comment by tomekk666** [comment]
I say we should look into Warlock spells in general and NOT necessarily stick to the rulebooks. They are nearly always built the same way, there's absolutely no point in varying up the spells because 70% of them are just bad 1 round crowd-controls which are simply inferior to Noxious' 10 round daze (and that doesn't mean Noxious is the culprit here, AA).

I'd also recommend the line of DC improving feats for Invocations, much like every other caster can take Spell Focus x3. As an added benefit, they could also carry with them an extra invocation slot, so you could add a bit more fun to your build by not just sticking to what's worth taking.

Hellfire Warlock in my honest opinion could also use a bit of a touch up, because now Undead can spam it with impunity whilst everyone else becomes more squishy than an undead from using it. A simple 2/3/4d6 damage AFTER (so as to not interrupt the spellcast immediately) casting the blast would be much more kind than slowly removing your level's worth of HP each second time you use it. And to counteract this, there could be a single-target only damage blast that siphons some of that HP back for you, so you don't have to rely on wands to patch yourself up, which I feel is just cheesy.

Also, agree with Taurus. 90% of warlocks don't have high Strength because they don't use Hideous Blast. Heavily encumbering them via their own invocations will just mean that no one will bother after realizing that.

**Comment by AgonyAunt** [comment]
@tomekk666 - Possibly. This one is definitely for Xndar to handle though, so ill remain fairly hands off except for approval/disapproval on final decisions.

When Xndar returns from their vacation ill poke them to get on GitHub so i can assign this issue to them.

**Comment by tomekk666** [comment]
Well, let's hope for the best then.

**Comment by Xndar** [comment]
Okay, I can edit the description for Baleful Geas to let folks know how it works. The STR penalty is an ability drain, and thus does not go away on its own without some curative magics...it also stacks. This was meant to somewhat simulate the fact that in PnP, eventually Baleful Geas kills the thrall. Will also look up the RP limitations of the control.

As for #2, I will up the str to 10, so there is no bonus or penalty. If they are, for some reason, a STR based warlock that runs about with fullplate, then maybe this invocation isn't for them.

**Comment by Xndar** [comment]
As for the Hellfire Warlocks, we should simply bar Undead or Constructs from taking the class. According to the rulebooks, if a creature is immune to ability drain, it CANNOT use Hellfire. Thus, how would a creature immune to ability drain be able to learn to master Hellfire enough to justify levels in the class?

**Comment by AgonyAunt** [comment]
Ok, sounds good.

As for hellfire warlock and undead/constructs - fair point. Separate issue though.

**Comment by tomekk666** [comment]
So, have any of my suggestions on the matter been considered?:p

**Comment by AgonyAunt** [comment]
Xndar has several projects on at the moment, but i would prefer if he made these tweaks sooner rather than later.

**Comment by Xndar** [comment]
Fixes to the issues raised by Taurus were included in my latest uploaded update. AA and I discussed Hellfire Warlock in another thread, and I've tested it with an Undead HW, and it still did the con damage regardless of the Deathknight's undead immunities.

As for the broader issues of DC improving feats etc, I know it can be done, as Fiendish and Fey power do so, but I would have to dig around a bit to see HOW exactly.

**Comment by AgonyAunt** [comment]
Excellent work Xndar.

**Comment by Xndar** [comment]
Nerull seems to be claiming that undead don't actually suffer con damage IG with Hellfire Warlocks. Not sure what the difference is between my test mod and the server, but just to cut out potential cheese, I will edit the HFW prereqs to preclude any undead or constructs from taking the class.

**Comment by Xndar** [comment]
Have come up with a quick fix, have uploaded on dropbox...all it needs is a tlk edit explicitly stating that undead and constructs are barred from the class.

**Comment by AgonyAunt** [comment]
Belay that fix. I've already done the direct damage changes.  Not sure how you prevent certain races from taking a class... i know you can make a certain class limited to a race or races... but, tell me you didn't edit the class by adding absoloutely every race we have except the undead and constructs and plants?

And besides, we already have HFW undead out there, so we would also have to flag them as illegal and force them to rebuild.  So i prefer the direct damage solution which relies on just replacing the scripts.
