### ISSUE TITLE
Vampires, lycanthropes, and chairs

### ISSUE THREAD

**Issue by Tamamo-no-Mae** [AgonyAunt/Sigil-City-of-Doors-PW#58]
Vampires [and werewolves/wererats] seem to refuse to perform chair animations for sitting.

**Comment by AgonyAunt** [comment]
In human form i guess you mean, since Dark Form won't have the animations.

I think Lycanthropes will have a similar issue. Its because the chairs check race to make sure they can do their anim.  I think i can fix this.

By the way, Kemo animations should work, so just position yourself near the chair, i think you might need to turn off collisions using the DMFI tool as well. The use kemo anims to sit.

**Comment by AgonyAunt** [comment]
Fixed.
