### ISSUE TITLE
Possible shapeshifting appearance problem solution

### ISSUE THREAD

**Issue by Tamamo-no-Mae** [AgonyAunt/Sigil-City-of-Doors-PW#74]
I understand this would take a very large amount of effort, but I have to wonder if it would be possible.

Would it be at all a viable solution to create an item a PC could use on a creature to store the appearance of the target, and then later, use to temporarily change their appearance into what is stored? Even better if they can store multiple--say, give three slots for it that can be named somehow--and choose between them.

Add an option to Styx in the OOC room to store a single appearance for a player, so that they could make another character just for the appearance, store it, then return to their main. Have the appearance values Styx is storing be cleared after ten minutes, or when stored in the item.

Have the item and Styx check the race of the user when attempting to store an appearance, and the race of the target appearance-holder. Then, if the combination is invalid (dragons can only transform into medium and smaller humanoids and animals, for instance, so no ogre-shape dragons), refuse to store the appearance in the item. (Styx would have to have the option to clear the appearance if it was rejected.)

**Comment by miriamchaturvedi** [comment]
I saw this done in NWN1, but several of the necessary functions around getting the head, hair, skin tone, etc. are now missing in NWN2. Only the base appearance type is accessible, which is useless for customizeable races. Maybe it could be done by hacking into the appearance changer code and re-purposing some of it, but such a solution would not be ideal.

**Comment by AgonyAunt** [comment]
It might be possible, but it would be quite flakey and would require a character to relog every time they changed their appearance. And there could be lots of side issues with potential of base character appearance becoming lost due to server crashes/lag/etc.

What is possible (and its something i had in mind for creating a Shifter/Master of Many Forms class) is simply copying the appearance of monsters in general.  This works in most cases, but as noted with the problem when we had vampires alternate forms as appearance changes things could go badly wrong due to head models not being present.  The only way to really make this work as a polymorph version is to make sure there is a lookup take for every appearance that matches an equivalent polymorph... and of course, then it also has polymorph limitation of no spellcasting etc.

So its a nice suggestion, but something that's not really feasible for something usable.  Think i have to close this one though.
