### ISSUE TITLE
Dragons & immunity to paralysis

### ISSUE THREAD

**Issue by Tamamo-no-Mae** [AgonyAunt/Sigil-City-of-Doors-PW#78]
"Immunities (Ex): All dragons have immunity to sleep and paralysis effects." - 3.5 SRD
Especially considering Dragon Disciples get this at 10th level, are dragons planned to get this immunity too?

**Comment by AgonyAunt** [comment]
I think not. IIRC this is because the RDD bonus feat comes as a single feat that covers all immunities (the Half-Dragon feat).

@Tamamo-no-Mae - I think i looked at this and found no way to easily implement immunity to paralysis via code as a single effect without making them immune to all hold type effects in the process. This would mean making them immune to the bigby spells, entanglement, and other stuff... which i don't think they should be immune to.  Correct me if im wrong.

Also correct me if the half-dragon feat doesn't give something that Dragons shouldn't get anyway... i'm thinking here immunity to fire, which would then give non-red/gold dragons and advantage over their red/gold counterparts by getting multiple immunities if i granted them the half-dragon feat itself.

Sorry if rambling... just back from vacations and responding to everything.  Responses might be confused, terse, impolite, and covered in detritus.

**Comment by ghost** [comment]
RDD gets it from FEAT_DRAGON_IMMUNE_PARALYSIS 963 surly the fire immunity comes from FEAT_DRAGON_IMMUNE_FIRE 964 ?

**Comment by AgonyAunt** [comment]
Ah, could be. Ill have to check it out.

**Comment by AgonyAunt** [comment]
Silly me, there was a racial immunity to paralysis feat available anyway and already granted to half-dragons.  Fixed now.
