### ISSUE TITLE
Add glove bonuses to creature weapons

### ISSUE THREAD

**Issue by Tamamo-no-Mae** [AgonyAunt/Sigil-City-of-Doors-PW#80]
Would it be possible to have gloves/bracers/whatever run a script on equipping that checks for enhancement/attack/damage bonuses on the glove, and if so, checking for creature weapons equipped... and if so, adding a temporary, undispellable bonus to the creature weapon to mimic the gloves? Upon unequip, just repeat the same thing, except if creature weapons are equipped, remove the bonuses from them.

**Comment by AgonyAunt** [comment]
Yes, but don't like the solution from a technical perspective. Already added similar code for the Sacred Fist code of conduct fix and also for the No Manual Dexterity feat.  Those are bad as it is because those checks are run every time any PC or NPC equips an item (including items created on spawn)... hate to add more to the script without good reason.  In this case, the only way to add the bonuses would be to apply directly to the creature, and these effects totally ignore all DR.  This would make races with creature weapons much more desirable as they would then be able to bypass DR much easier.

I'm afraid i still don't have a good solution for this whole problem of creature weapons/gloves/bracers.

I feel its best left as a knowledge point documented on the wiki that certain things don't work and the option for those who don't want to deal with creature weapons can always get them removed. (pluses and minuses on this choice depending on build - eg: Monk better unarmed, Druid better with Creature weapons, Monk/Druid...errr, take your pick).

Closing.
