### ISSUE TITLE
Plant wildshapes use myconid racial type

### ISSUE THREAD

**Issue by Tamamo-no-Mae** [AgonyAunt/Sigil-City-of-Doors-PW#82]
This is a bit of a problem, because it also applies the myconid's racial ability adjustments.

**Comment by AgonyAunt** [comment]
Are you certain, i think what you are seeing is what is in base game. Plant Wildshapes should have plant racial type of course and get the immunities. This is why Plant Wildshape is often considered superior to other forms, just because of this.  They shouldn't get the myconids ability adjustments applied, although they may be the same/similiar.

Compare polymorph.2da, look at the entry for the plant wildshapes racial type and ability values.

**Comment by AgonyAunt** [comment]
In fact, i'm quite intimate with the wildshape/polymorph functions scripts. What you are suggesting shouldn't even be possible from a code perspective.

**Comment by Tamamo-no-Mae** [comment]
"shouldn't even be possible from a code perspective"
Never underestimate Obsidian!

So it's set to use Plant as the racial type, but the racial subtype is Myconid for some reason. Myconid appears as the race on the character sheet. Tested with a wildshaping Nymph, no gear or spell effects: shifting into a plant reduced INT by 6 (Nymph: +6 / Myconid: +0), reduced WIS by 2 (Nymph: +6 / Myconid: +4), and CHA by 4 (Nymph: +8 / Myconid: +4).

Is there anything else that could be causing that?

**Comment by AgonyAunt** [comment]
Totally bizarre... shouldn't be happening.  But ill look into it.

**Comment by AgonyAunt** [comment]
Ah ha... i think i understand what is going on, and this also would have affected Dragon Wildshape if anyone had noticed it, and Magical Beast as well. Basically when you polymorph it looks like indeed it can also take on a sub-type for properties.  This is based off the DefaultSubType column of RacialTypes.2da.  For Dragons, Plants, and Magical Beasts i had changed these values to a selected playable race, so that when selecting your race it would be default show one of the options without having to click on it.  In the case of Plants i'd set this to Myconids.

Therefore i have reset these values back to point to the default sub-races which have no custom values.

However, this is very interesting and actually enables the ability to set INT, CHA, and WIS values on polymorph, something which is not allowed by polymorph.2da (where you can only set physical stats).  If you were to create a polymorph pointing to a custom race with a custom default sub-race then you could have polymorphs give different mental values.  The problem with this is for things like FE and item properties that are race dependent - these would then not be considered. ie: polymorph to custom race "Hobbit", there is no Favoured Enemy: Hobbit.

Interesting regardless.
